spring:
 datasource:
   driver-class-name: org.h2.Driver
   url: jdbc:h2:mem:testdb
   username: sa
   password: '{cipher}AQB2J0IP57+8Mwa9ee6SsgiH/LP7F7GM19r26QT0Aha5zYIVitk3+wVv8ZllIt7wH61gCFFSFiEwWYRwRFHAQNfCNdxzKi/6T4cS3u9b85JF4o1d52QtQNu5ThhJhwerT/TKX/ZzqDoLmei0+rthQ7X2ewlBHD544bHmrG5nXmgIKMWa30JRWYcV6jyqvg+1bKs3uS/VJ34G4AGozkIbYSj+ocLmia49TvCWo0yjO0Jo03PmZPVp7wkfUbnrKe6e/VlnL7R9Cl159XWdDa8oqvPrt0IqTQuCfHCLN3e/QCk3p28JlvRHXc64UOB5d5fP3qV/2xy7faHnt8YCaJpZYBz02AfPqnc0MN5vMF8L790YLyhs4eV2uospcsJ4eg0+Hrw='

order-service:
  url: http://ORDER-SERVICE:8000/order-service/%s/orders
